// 'use client';
import ResponsiveAppBar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import IconBreadcrumbs from '@/components/Breadcrumbs';
import { Box } from '@mui/material';
import Dashboard from '@/components/Dashboard';
import ResponsiveDrawer from '@/components/Drawer';
import Container from '@/components/Container';
import { useLoadingStore } from '@/stores/loadingStore';
import Loading from '@/components/Loading/Loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const setLoading = useLoadingStore((state) => state.setLoading);
  // const loading = useLoadingStore((state) => state.loading);

  // if (loading) return <Loading />;

  return (
    <html lang='en'>
      <body className={inter.className}>
        <ResponsiveDrawer
          drawerChildren={
            <Box>
              <Dashboard />
            </Box>
          }
        >
          <IconBreadcrumbs />
          <Container>{children}</Container>
        </ResponsiveDrawer>
      </body>
    </html>
  );
}
